# Generated by Django 5.0.1 on 2024-02-21 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_category_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='slug',
            field=models.SlugField(blank=True),
        ),
        migrations.AddField(
            model_name='cardproduct',
            name='slug',
            field=models.SlugField(blank=True),
        ),
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True),
        ),
        migrations.AddField(
            model_name='productimage',
            name='slug',
            field=models.SlugField(blank=True),
        ),
        migrations.AddField(
            model_name='productreview',
            name='slug',
            field=models.SlugField(blank=True),
        ),
        migrations.AddField(
            model_name='wishlist',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
